import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { Nav } from "@/components/tidly/Nav";
import { getCleanerBySlug } from "@/lib/cleaners.functions";
const SITE_URL="https://amanda-cleaning.lovable.app";
const AUDIENCE_LABEL:Record<string,string>={home:"Homes",rental:"Airbnb & rentals",move:"Move-in / move-out"};
const cleanerQuery=(slug:string)=>queryOptions({queryKey:["cleaner",slug],queryFn:()=>getCleanerBySlug({data:{slug}})});
export const Route=createFileRoute("/cleaners/$slug")({loader:async({params,context})=>{const cleaner=await context.queryClient.ensureQueryData(cleanerQuery(params.slug));if(!cleaner)throw notFound();return{cleaner}},head:({loaderData,params})=>{if(!loaderData)return{meta:[{title:"Cleaner not found — Amaneat"},{name:"robots",content:"noindex"}]};const c=loaderData.cleaner;const title=`${c.display_name} — Amaneat cleaner in Tampa`;const description=c.headline??`Meet ${c.display_name}, a professional cleaner in the Amaneat Tampa network.`;return{meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},...(c.photo_url?[{property:"og:image",content:c.photo_url}]:[])],links:[{rel:"canonical",href:`${SITE_URL}/cleaners/${params.slug}`}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Person",name:c.display_name,image:c.photo_url??undefined,jobTitle:"Professional cleaner",worksFor:{"@type":"Organization",name:"Amaneat"},areaServed:c.zips.map(z=>({"@type":"PostalAddress",addressLocality:"Tampa",addressRegion:"FL",addressCountry:"US",postalCode:z})),aggregateRating:{"@type":"AggregateRating",ratingValue:c.rating,reviewCount:c.review_count}})}]}} ,component:CleanerDetail,notFoundComponent:NotFoundCleaner});
function CleanerDetail(){const{slug}=Route.useParams();const{data:cleaner}=useSuspenseQuery(cleanerQuery(slug));if(!cleaner)return <NotFoundCleaner/>;return <div className="min-h-screen bg-background text-foreground"><Nav/><section className="mx-auto max-w-3xl px-5 py-14 md:px-8 md:py-20"><nav aria-label="Breadcrumb" className="text-xs text-muted-foreground"><Link to="/">Home</Link><span className="mx-1.5">/</span><Link to="/cleaners">Cleaners</Link><span className="mx-1.5">/</span><span>{cleaner.display_name}</span></nav><div className="mt-8 flex flex-col gap-6 md:flex-row md:items-center">{cleaner.photo_url?<img src={cleaner.photo_url} alt={cleaner.display_name} className="h-28 w-28 rounded-3xl object-cover md:h-36 md:w-36"/>:<div className="grid h-28 w-28 place-items-center rounded-3xl bg-secondary text-3xl font-semibold text-muted-foreground">{cleaner.display_name.slice(0,1)}</div>}<div><h1 className="text-3xl font-semibold tracking-tight md:text-4xl">{cleaner.display_name}</h1>{cleaner.headline&&<p className="mt-2 text-base text-muted-foreground">{cleaner.headline}</p>}<p className="mt-3 text-sm text-muted-foreground"><span className="text-primary">★ {cleaner.rating.toFixed(1)}</span> · {cleaner.review_count} reviews{cleaner.years_experience?` · ${cleaner.years_experience}+ yrs`:""}</p></div></div>{cleaner.bio&&<div className="mt-10">{cleaner.bio.split("\n").map((p,i)=><p key={i} className="mb-3 text-base leading-relaxed text-foreground/90">{p}</p>)}</div>}<div className="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-3"><Facet title="Services">{cleaner.audiences.map(a=><Chip key={a}>{AUDIENCE_LABEL[a]??a}</Chip>)}</Facet><Facet title="Tampa-area ZIPs">{cleaner.zips.map(z=><Chip key={z}>{z}</Chip>)}</Facet><Facet title="Languages">{cleaner.languages.map(l=><Chip key={l}>{l.toUpperCase()}</Chip>)}</Facet></div><div className="mt-12 flex flex-wrap gap-3"><Link to="/chat" className="rounded-full bg-primary px-6 py-3 text-sm font-medium text-primary-foreground">Book with Amaneat</Link><Link to="/cleaners" className="rounded-full border border-input px-6 py-3 text-sm font-medium">All cleaners</Link></div></section></div>}
function Facet({title,children}:{title:string;children:React.ReactNode}){return <div><p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">{title}</p><div className="mt-3 flex flex-wrap gap-2 text-xs">{children}</div></div>}
function Chip({children}:{children:React.ReactNode}){return <span className="rounded-full border border-border bg-card px-2.5 py-1 text-xs text-foreground">{children}</span>}
function NotFoundCleaner(){return <div className="min-h-screen bg-background"><Nav/><div className="mx-auto max-w-2xl px-5 py-20 text-center"><h1 className="text-2xl font-semibold">Cleaner not found</h1><Link to="/cleaners" className="mt-6 inline-block text-primary hover:underline">See all cleaners</Link></div></div>}
